image: node:alpine

cache:
  paths:
  - node_modules/

pages:
  script:
  - yarn
  - PUBLIC_URL="https://sca-drachenwald.gitlab.io/university/" yarn build
  - rm -rf public
  - mv build public
  artifacts:
    expire_in: 1 hour
    paths:
    - public
  only:
  - staging
